name: Scheduled Playwright Tests
permissions:
  contents: read

on:
  schedule:
    - cron: "30 3 * * 1-6"
  workflow_dispatch:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      # 🔥 IMPORTANT STEP – Install Playwright browsers + deps
      - name: Install Playwright browsers & dependencies
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      # ▶️ Run tests
      - name: Run Playwright Tests
        run: mvn clean test
